// <auto-generated />
namespace FoodAppDALLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class reqiredvalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reqiredvalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202403090200229_reqired validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
