// <auto-generated />
namespace FoodAppDALLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class totalavailableqytinfooditems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(totalavailableqytinfooditems));
        
        string IMigrationMetadata.Id
        {
            get { return "202403080122349_total available qyt in fooditems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
