// <auto-generated />
namespace FoodAppDALLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class foodimagetobytetostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foodimagetobytetostring));
        
        string IMigrationMetadata.Id
        {
            get { return "202403060719350_foodimage to byte to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
